version: '3.7'
services:
    postgres:
        container_name: test_postgres_docker
        image: postgres
        restart: always
        environment:
            "POSTGRES_PASSWORD": "postgres"
            "POSTGRES_USER": "postgres"
            "POSTGRES_DB": "sampledb"
        ports:
            - '5432-5435:5432-5435'
        volumes:
            - ./data/pg_data/postgres/:/var/lib/postgresql/data
            - ./data/pg_data/init.sql:/docker-entrypoint-initdb.d/init.sql
    mongodb_container:
        container_name: test_mongodb_docker
        image: mongo:latest
        restart: always
        environment:
            MONGO_INITDB_ROOT_DATABASE: sampledb
            MONGO_INITDB_ROOT_USERNAME: sample
            MONGO_INITDB_ROOT_PASSWORD: samplepassword
        ports:
            - '27017-27019:27017-27019'
        volumes:
            - ./data/mongodb_data/:/data/db
            - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            
volumes:
    mongodb_data:
